apiVersion: carto.run/v1alpha1
kind: Workload
metadata:
  name: sample-app-java
  labels:
    apps.tanzu.vmware.com/workload-type: web
spec:
  params:
    - name: run-image
      value: harbor-repo.vmware.com/tanzu_desktop/sample-app-java
  source:
    git:
      url: https://github.com/sample-accelerators/tanzu-java-web-app
      ref:
        branch: main
